# Generated by Django 5.2.7 on 2025-10-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlipIQ_APP', '0004_session_participant_submission_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
